# Target unit map - ensure up to date

TARGET_UNITS: dict[str, str] = {
    "Mineralen delen ten opzichte DS":       "%",
    "Zand (63um < fractie < 2mm)":           "%",
    "(250um < fractie < 2mm)":               "%",
    "(63um < fractie < 250um)":              "%",
    "Silt (2um < fractie < 63um)":           "%",
    "(20 < fractie < 63um)":                 "%",
    "Leemfractie (fractie < 10um)":          "%",
    "Lutum (fractie < 2um)":                 "%",
    "Leem (lutum+silt)":                     "%",
    "Korrelverdeling (D60/D10)":             "-",
    "Korrelverdeling (M50)":                 "um",
    "Gehalte organische koolstof (TOC)":     "%",
    "Gehalte organische stof":               "%",
    "Kalk (CaCO3)":                          "%",
    "pH-waarde":                             "pH",
    "Grof materiaal (fractie)":              "%",
    "Bodemvreemd":                           "",
    "Fosfor totaal (destructie)":            "mg P/kg",
    "Fosfor beschikbaar":                    "mg P/kg",
    "Stikstof totaal (N-Kjeldahl)":          "mg N/kg",
    "Ammonium totaal":                       "mg NH4+/kg",
    "Stikstof levering":                     "kg N/ha",
    "C/N verhouding":                        "-",
    "Zwavel totaal":                         "%",
    "Zwavel beschikbaar":                    "mg S/kg",
    "Wateroplosbare Zouten (chloride)":      "%",
    "CEC":                                   "mmol+/kg",
    "CEC bezetting totaal":                  "%",
    "CEC bezetting calcium":                 "%",
    "CEC bezetting kalium":                  "%",
    "CEC bezetting magnesium":               "%",
    "Kalium totaal":                         "mmol+/kg",
    "Kalium beschikbaar":                    "mg K/kg",
    "Magnesium totaal":                      "mmol+/kg",
    "Magnesium beschikbaar":                 "mg Mg/kg",
    "Calcium totaal":                        "mmol+/kg",
    "Calcium beschikbaar":                   "mmol Ca/L",
    "Aluminium totaal":                      "mg Al/kg",
    "Natrium totaal":                        "mmol+/kg",
    "Zink totaal":                           "ug/kg",
    "Koper totaal":                          "ug/kg",
}